# Generated by Django 5.0.1 on 2024-02-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
    ]
